const photo = (id) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=800&q=70`;

const address = (city, state, pin) => ({
  pinCode: pin,
  streetName: '',
  area: '',
  city,
  district: '',
  state,
  country: 'India'
});

export function buildSeed({ officeHash, memberHash }) {
  const users = [
    {
      id: 'u-admin',
      email: 'admin@example.com',
      phone: '9440545049',
      firstName: 'Office',
      lastName: 'Admin',
      surname: 'Admin',
      passwordHash: officeHash,
      role: 'admin',
      status: 'active'
    },
    user('u-anitha', 'anitha.demo@example.com', '9000000001', 'Anitha', 'Rao', memberHash),
    user('u-suresh', 'suresh.demo@example.com', '9000000002', 'Suresh', 'Babu', memberHash),
    user('u-mary', 'mary.demo@example.com', '9000000003', 'Mary', 'Kumari', memberHash),
    user('u-praveen', 'praveen.demo@example.com', '9000000004', 'Praveen', 'Kumar', memberHash),
    user('u-lakshmi', 'lakshmi.demo@example.com', '9000000005', 'Lakshmi', 'Devi', memberHash),
    user('u-ravi', 'ravi.demo@example.com', '9000000006', 'Ravi', 'Teja', memberHash),
    user('u-kavya', 'kavya.demo@example.com', '9000000007', 'Kavya', 'Sri', memberHash),
    user('u-naresh', 'naresh.demo@example.com', '9000000008', 'Naresh', 'Varma', memberHash),
    user('u-pending', 'pending.demo@example.com', '9000000009', 'Arun', 'Kumar', memberHash),
    user('u-kiran', 'kiran.demo@example.com', '9000000010', 'Kiran', 'Reddy', memberHash)
  ];

  const profiles = [
    profile({
      id: 'p1',
      profileId: 'F00001',
      userId: 'u-anitha',
      gender: 'female',
      dateOfBirth: '2000-04-12',
      heightFeet: 5,
      heightInches: 4,
      religion: 'Hindu',
      motherTongue: 'Telugu',
      maritalStatus: 'Nevermarried',
      highestEducation: 'B.A',
      fieldOfStudy: 'Education',
      occupation: 'Teacher',
      employmentType: 'private',
      companyName: 'A local school',
      income: 480000,
      jobLocation: 'Vijayawada',
      city: 'Vijayawada',
      state: 'Andhra Pradesh',
      pin: '520004',
      aboutMe: 'I teach primary classes in Vijayawada and live with my parents. Family values and a calm home matter most to us.',
      partnerRequirement: 'A respectful groom, preferably in Andhra Pradesh, whose family is comfortable meeting at the Vijayawada office.',
      photo: photo('photo-1544005313-94ddf0286df2')
    }),
    profile({
      id: 'p2',
      profileId: 'M00002',
      userId: 'u-suresh',
      gender: 'male',
      dateOfBirth: '1997-08-03',
      heightFeet: 5,
      heightInches: 10,
      religion: 'Hindu',
      motherTongue: 'Telugu',
      maritalStatus: 'Nevermarried',
      highestEducation: 'B.Tech',
      fieldOfStudy: 'Civil engineering',
      occupation: 'Engineer',
      employmentType: 'private',
      companyName: 'A construction firm',
      income: 900000,
      jobLocation: 'Guntur',
      city: 'Guntur',
      state: 'Andhra Pradesh',
      pin: '522001',
      aboutMe: 'I work as a site engineer in Guntur. My parents are looking for a bride from a Mala family.',
      partnerRequirement: 'A kind bride with a steady education. Age and city can be discussed with both families.',
      photo: photo('photo-1506794778202-cad84cf45f1d')
    }),
    profile({
      id: 'p3',
      profileId: 'F00003',
      userId: 'u-mary',
      gender: 'female',
      dateOfBirth: '1999-01-19',
      heightFeet: 5,
      heightInches: 3,
      religion: 'Christian',
      motherTongue: 'Telugu',
      maritalStatus: 'Nevermarried',
      highestEducation: 'B.Sc',
      fieldOfStudy: 'Nursing',
      occupation: 'Nurse',
      employmentType: 'private',
      companyName: 'A city hospital',
      income: 540000,
      jobLocation: 'Vijayawada',
      city: 'Vijayawada',
      state: 'Andhra Pradesh',
      pin: '520010',
      aboutMe: 'I am a staff nurse. Faith and family prayer are part of our home.',
      partnerRequirement: 'A Christian Mala groom whose family will meet ours before any decision.',
      photo: photo('photo-1524504388940-b1c1722653e1')
    }),
    profile({
      id: 'p4',
      profileId: 'M00004',
      userId: 'u-praveen',
      gender: 'male',
      dateOfBirth: '1995-11-22',
      heightFeet: 5,
      heightInches: 11,
      religion: 'Hindu',
      motherTongue: 'Telugu',
      maritalStatus: 'Nevermarried',
      highestEducation: 'M.Tech',
      fieldOfStudy: 'Computer science',
      occupation: 'IT professional',
      employmentType: 'private',
      companyName: 'A software company',
      income: 1800000,
      jobLocation: 'Hyderabad',
      city: 'Hyderabad',
      state: 'Telangana',
      pin: '500081',
      aboutMe: 'I work in Hyderabad and visit my parents in Vijayawada most months.',
      partnerRequirement: 'An educated bride. We are happy to begin with a meeting at the Vijayawada office.',
      photo: photo('photo-1500648767791-00dcc994a43e')
    }),
    profile({
      id: 'p5',
      profileId: 'F00005',
      userId: 'u-lakshmi',
      gender: 'female',
      dateOfBirth: '2002-02-02',
      heightFeet: 5,
      heightInches: 2,
      religion: 'Hindu',
      motherTongue: 'Telugu',
      maritalStatus: 'Nevermarried',
      highestEducation: 'M.Sc',
      fieldOfStudy: 'Mathematics',
      occupation: 'Lecturer',
      employmentType: 'private',
      companyName: 'A degree college',
      income: 420000,
      jobLocation: 'Guntur',
      city: 'Guntur',
      state: 'Andhra Pradesh',
      pin: '522002',
      aboutMe: 'I lecture in mathematics. My parents are completing this search with me.',
      partnerRequirement: 'A groom with a stable job, from Andhra Pradesh or Telangana.',
      photo: photo('photo-1531123897727-8f129e1688ce')
    }),
    profile({
      id: 'p6',
      profileId: 'M00006',
      userId: 'u-ravi',
      gender: 'male',
      dateOfBirth: '1998-05-30',
      heightFeet: 5,
      heightInches: 9,
      religion: 'Hindu',
      motherTongue: 'Telugu',
      maritalStatus: 'Nevermarried',
      highestEducation: 'B.Tech',
      fieldOfStudy: 'Information technology',
      occupation: 'Software engineer',
      employmentType: 'private',
      companyName: 'A product company',
      income: 2200000,
      jobLocation: 'Bengaluru',
      city: 'Bangalore',
      state: 'Karnataka',
      pin: '560001',
      aboutMe: 'I work in Bengaluru. My parents live in Vijayawada and will attend the first meeting.',
      partnerRequirement: 'A Telugu bride. Parents may lead the conversation.',
      photo: photo('photo-1507003211169-0a1dd7228f2d')
    }),
    profile({
      id: 'p7',
      profileId: 'F00007',
      userId: 'u-kavya',
      gender: 'female',
      dateOfBirth: '1996-09-14',
      heightFeet: 5,
      heightInches: 5,
      religion: 'Buddhist',
      motherTongue: 'Telugu',
      maritalStatus: 'Divorced',
      highestEducation: 'MBA',
      fieldOfStudy: 'Finance',
      occupation: 'Accountant',
      employmentType: 'private',
      companyName: 'A finance office',
      income: 700000,
      jobLocation: 'Visakhapatnam',
      city: 'Visakhapatnam',
      state: 'Andhra Pradesh',
      pin: '530001',
      aboutMe: 'This is a second-marriage search, handled quietly with my parents.',
      partnerRequirement: 'A kind groom who understands a second marriage. Privacy is important to our family.',
      photo: photo('photo-1487412720507-e7ab37603c6f')
    }),
    profile({
      id: 'p8',
      profileId: 'M00008',
      userId: 'u-naresh',
      gender: 'male',
      dateOfBirth: '1993-12-01',
      heightFeet: 6,
      heightInches: 0,
      religion: 'Ambedkarist',
      motherTongue: 'Telugu',
      maritalStatus: 'Nevermarried',
      highestEducation: 'MBA',
      fieldOfStudy: 'Management',
      occupation: 'Bank officer',
      employmentType: 'public',
      companyName: 'A public sector bank',
      income: 1100000,
      jobLocation: 'United States',
      city: 'NRI',
      state: 'Andhra Pradesh',
      pin: '520001',
      aboutMe: 'I work abroad and my parents in Vijayawada are leading the search.',
      partnerRequirement: 'A Telugu bride willing to consider an NRI life after both families meet.',
      photo: photo('photo-1492562080023-ab3db95bfbce')
    }),
    profile({
      id: 'p9',
      profileId: null,
      userId: 'u-pending',
      gender: 'male',
      dateOfBirth: '1999-07-07',
      heightFeet: 5,
      heightInches: 8,
      religion: 'Hindu',
      motherTongue: 'Telugu',
      maritalStatus: 'Nevermarried',
      highestEducation: 'B.Com',
      fieldOfStudy: 'Commerce',
      occupation: 'Accountant',
      employmentType: 'private',
      companyName: 'A local firm',
      income: 360000,
      jobLocation: 'Vijayawada',
      city: 'Vijayawada',
      state: 'Andhra Pradesh',
      pin: '520004',
      aboutMe: 'Waiting for the Vijayawada office to check this biodata.',
      partnerRequirement: 'A bride from Vijayawada or Guntur.',
      photo: photo('photo-1472099645785-5658abf4ff4e'),
      approvalStatus: 'pending',
      showInSearch: false
    }),
    profile({
      id: 'p10',
      profileId: 'M00010',
      userId: 'u-kiran',
      gender: 'male',
      dateOfBirth: '1994-03-18',
      heightFeet: 5,
      heightInches: 9,
      religion: 'Hindu',
      motherTongue: 'Telugu',
      maritalStatus: 'Nevermarried',
      highestEducation: 'B.Tech',
      fieldOfStudy: 'Mechanical engineering',
      occupation: 'Engineer',
      employmentType: 'private',
      companyName: 'A workshop in Vijayawada',
      income: 750000,
      jobLocation: 'Vijayawada',
      city: 'Vijayawada',
      state: 'Andhra Pradesh',
      pin: '520004',
      aboutMe: 'I work in Vijayawada and live with my parents in Machavaram.',
      partnerRequirement: 'A bride from Vijayawada or a nearby town. Both families can meet at the office.',
      photo: photo('photo-1463453091185-61582044d556')
    })
  ];

  return {
    seq: 10,
    users,
    profiles,
    interests: [
      {
        id: 'i1',
        fromUserId: 'u-suresh',
        toProfileId: 'p1',
        status: 'pending',
        createdAt: '2026-09-01T10:00:00.000Z'
      }
    ],
    resets: []
  };
}

function user(id, email, phone, firstName, surname, passwordHash) {
  return {
    id,
    email,
    phone,
    firstName,
    lastName: surname,
    surname,
    passwordHash,
    role: 'user',
    status: 'active'
  };
}

function profile(input) {
  return {
    id: input.id,
    profileId: input.profileId,
    userId: input.userId,
    approvalStatus: input.approvalStatus || 'approved',
    showInSearch: input.showInSearch !== false && (input.approvalStatus || 'approved') === 'approved',
    gender: input.gender,
    dateOfBirth: input.dateOfBirth,
    heightFeet: input.heightFeet,
    heightInches: input.heightInches,
    religion: input.religion,
    subCaste: 'SC',
    caste: 'Mala',
    motherTongue: input.motherTongue,
    maritalStatus: input.maritalStatus,
    siblingsCount: 1,
    fatherName: 'Parent',
    fatherOccupation: 'Retired',
    motherName: 'Parent',
    motherOccupation: 'Homemaker',
    highestEducation: input.highestEducation,
    fieldOfStudy: input.fieldOfStudy,
    college: 'A college in Andhra Pradesh',
    occupation: input.occupation,
    employmentType: input.employmentType,
    companyName: input.companyName,
    jobTitle: input.occupation,
    jobLocation: input.jobLocation,
    industry: 'General',
    income: input.income,
    incomeCurrency: 'INR',
    currentAddress: address(input.city, input.state, input.pin),
    presentAddress: address(input.city, input.state, input.pin),
    nativePlace: input.city,
    fatherNativePlace: 'Vijayawada',
    motherNativePlace: 'Vijayawada',
    aboutMe: input.aboutMe,
    partnerRequirement: input.partnerRequirement,
    photos: [{ url: input.photo, isPrimary: true }],
    membershipType: 'premium',
    hideMobile: true,
    profileViews: 0,
    interestCount: 0
  };
}
